name: 其他问题 / Other Issue
description: 其他类型的问题或疑问 / Other types of issues or questions
labels: ["question"]
body:
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: |
        请详细描述您的问题
    validations:
      required: false

  - type: input
    id: device-info
    attributes:
      label: 设备环境 / Device Environment
      description: 请填写设备类型 (手机/平板/PC) 及具体型号。 (Device type and model.)
      placeholder: 例如：PC / iPhone 15 / iPad Air
    validations:
      required: false

  - type: input
    id: browser-os
    attributes:
      label: 浏览器与系统 / Browser & OS
      description: 例如：Chrome 122 / Windows 11 / iOS Safari
      placeholder: e.g. Chrome 122 / Windows 11
    validations:
      required: false


  - type: textarea
    id: additional
    attributes:
      label: 截图与补充信息 / Screenshots & Context
    validations:
      required: false
